version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    entrypoint: "/serve/main -listen 0.0.0.0:8000"
    working_dir: "/serve"

  database:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
