version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile_dev
    ports:
      - 8000:8000
    entrypoint: "/serve/main -listen 0.0.0.0:8000 -dev-mode"
    working_dir: "/serve"
    volumes:
      - "./ui/public:/serve/ui"

  database:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
