name: Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker login
        run: "docker login docker.pkg.github.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: "$GITHUB_ACTOR"
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: "docker build -t docker.pkg.github.com/preetam/readfasterapp/app:$GITHUB_SHA -t docker.pkg.github.com/preetam/readfasterapp/app:latest ."
      - name: Push image to GitHub Packages
        run: "docker push docker.pkg.github.com/preetam/readfasterapp/app:$GITHUB_SHA"
      - name: Push image to GitHub Packages
        run: "docker push docker.pkg.github.com/preetam/readfasterapp/app:latest"
      # - name: Perform ShiftLeft Scan
      #   uses: ShiftLeftSecurity/scan-action@master
      #   with:
      #     type: "credscan,java,depscan"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ansible
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
